Made logo file customizable
aiidalab/ansible-role-aiidalab-server pull request #44
Opened 2023-09-14 11:18 UTC by Crivella

Logo can now be chosen in a playbook importing this role by overwriting the `aiidalab_logo_file` variable

2023-09-16 09:46 UTC, ltalirz commented
Hi @Crivella , thanks for the contribution; I am not sure who is currently maintaining this role

@yakutovicha possibly?

2023-09-25 13:50 UTC, yakutovicha requested changes

2023-09-25 13:50 UTC, yakutovicha commented on tasks/jupyterhub.yml
> +    src: "{{ aiidalab_apache_config }}"
Should it not be `aiidalab_logo_file`?

2023-09-25 14:57 UTC, Crivella commented on tasks/jupyterhub.yml
> +    src: "{{ aiidalab_apache_config }}"
Yes i fixed it sorry

2023-09-25 15:02 UTC, yakutovicha approved these changes

2023-09-25 15:03 UTC, merged