[WIP] Synchronize with openstack-ansible repo
aiidalab/ansible-role-aiidalab-server pull request #7
Opened 2019-11-05 13:20 UTC by yakutovicha

2019-11-05 16:41 UTC, ltalirz commented on files/merge_app_metadata.py
> +from __future__ import print_function
could you please add a docstring that explains what this script does?

2019-11-05 16:41 UTC, ltalirz commented on tasks/jupyterhub.yml
> +  when: aiidalab_server_users_home_drive is defined
```suggestion
  when: aiidalab_server_os_volume is defined
```

2019-11-05 16:46 UTC, ltalirz requested changes
thanks @yakutovicha for the additions & fixes, some minor requests from my side.

please also see the travis failure https://travis-ci.org/marvel-nccr/ansible-role-aiidalab-server/jobs/607637221#L423

see here for how to run the test locally
https://github.com/marvel-nccr/ansible-role-aiidalab-server#tests

2019-11-05 16:46 UTC, ltalirz commented on tasks/jupyterhub.yml
> +    vol_name: "{{ aiidalab_server_users_home_drive }}"
```suggestion
    vol_name: "{{ aiidalab_server_os_volume }}"
```

2019-11-05 16:46 UTC, ltalirz commented on tasks/jupyterhub.yml
> +    vol_size: "{{ aiidalab_server_users_home_drive_size }}"
```suggestion
    vol_size: "{{ aiidalab_server_os_volume_size }}"
```

2019-11-05 16:46 UTC, ltalirz commented on tasks/jupyterhub.yml
> +  when: aiidalab_server_users_home_drive is defined
Please also put both variables (os_volume and os_volume_size) in the `defaults.yml` ( commented out) so that people know they exist

2019-11-05 16:46 UTC, ltalirz commented on tasks/main.yml
> +- import_tasks: app-metadata.yml
is this part necessary?
since this has been producing problems so often, I would prefer to keep this optional if possible.

e.g. have something like `when: aiidalab_server_metadata_daemon`

2019-11-05 16:46 UTC, ltalirz commented on tasks/prerequisites.yml
> +      version: 1.0.0
Cool!

2019-11-05 16:46 UTC, ltalirz commented on tasks/prerequisites.yml
> +      version: 1.0.0
I guess this requires jupyterhub 1.0 in the image as well.

2019-11-07 17:24 UTC, yakutovicha commented on files/merge_app_metadata.py
> +from __future__ import print_function
done

2019-11-07 17:34 UTC, yakutovicha commented on tasks/jupyterhub.yml
> +  when: aiidalab_server_users_home_drive is defined
done

2019-11-07 17:34 UTC, yakutovicha commented on tasks/jupyterhub.yml
> +    vol_name: "{{ aiidalab_server_users_home_drive }}"
done

2019-11-07 17:35 UTC, yakutovicha commented on tasks/jupyterhub.yml
> +    vol_size: "{{ aiidalab_server_users_home_drive_size }}"
done

2019-11-07 17:36 UTC, yakutovicha commented on tasks/prerequisites.yml
> +      version: 1.0.0
Yes, this is done in the image as well

2019-11-07 17:38 UTC, yakutovicha commented on tasks/main.yml
> +- import_tasks: app-metadata.yml
done

2019-11-07 18:10 UTC, merged